name: heyjoyhey
favicon: null
layout_spectrum: 0.803913825424388
typography_spectrum: 0.06625748961232603
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.8773260933812708
  lightness: 0.2746899239718914
  saturation: 0.6316151404753327
  rhythmicContrast: 0.43232617690227926
purpose: []
